#For the development and code testing
name: Package Build and Test

on:
  push:
    branches:
      - main 

permissions:
  contents: write

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Dependencies (Development Mode)
        run: |
          poetry install --no-root
      
      - name: Install Black
        run: |
          pip install black

      - name: Check Formatting (Optional)
        run: |
          poetry --check

      - name: Linting (Optional)
        run: |
          poetry run flake8 .

      - name: Type Checking (Optional)
        run: |
          poetry run mypy .

      - name: Verify Build
        run: |
          poetry build
